server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/payment
spring.datasource.username=payment
spring.datasource.password=payment
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=quizzler-mq
spring.rabbitmq.password=quizzler-mq
spring.rabbitmq.virtual-host=quizzler
