server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/quizzler
spring.datasource.username=quizzler
spring.datasource.password=quizzler
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

payment.api.base-url=http://localhost:8081
quizzler.api.base-url=http://localhost:8080
quizzler.ui.base-url=http://localhost:4200

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=quizzler-mq
spring.rabbitmq.password=quizzler-mq
spring.rabbitmq.virtual-host=quizzler

spring.rabbitmq.listener.simple.default-requeue-rejected=false
